#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sigar
Version  : 1.6.4
Release  : 1
URL      : http://repo1.maven.org/maven2/org/fusesource/sigar/1.6.4/sigar-1.6.4-sources.jar
Source0  : http://repo1.maven.org/maven2/org/fusesource/sigar/1.6.4/sigar-1.6.4-sources.jar
Source1  : http://repo1.maven.org/maven2/org/fusesource/sigar/1.6.4/sigar-1.6.4.jar
Source2  : http://repo1.maven.org/maven2/org/fusesource/sigar/1.6.4/sigar-1.6.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-sigar-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sigar package.
Group: Data

%description data
data components for the mvn-sigar package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4-sources.jar
/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4.jar
/usr/share/java/.m2/repository/org/fusesource/sigar/1.6.4/sigar-1.6.4.pom
